-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Feb 20, 2014 at 08:22 AM
-- Server version: 5.5.35
-- PHP Version: 5.3.10-1ubuntu3.9

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `agar_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `page`
--

CREATE TABLE IF NOT EXISTS `page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` int(11) NOT NULL,
  `title` varchar(512) CHARACTER SET utf8 NOT NULL,
  `text` text CHARACTER SET utf8 NOT NULL,
  `cols` enum('no','yes') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`id`),
  KEY `type` (`type`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=34 ;

--
-- Dumping data for table `page`
--

INSERT INTO `page` (`id`, `type`, `title`, `text`, `cols`) VALUES
(1, 1, 'SCURT ISTORIC', '                    		    			    	<p>		    	2007 - este infiintata compania;<br>2008 - compania incepe activitatea prin investitii auto si imobiliare din surse proprii ajungand la sfarsitul anului la un patrimoniu de 35 de automobile si 2 apartamente in zona ultracentrala a Timisoarei cu care demareaza serviciile de inchiriere ce continua pana in prezent; tot in acest an compania incepe investitia in terenuri agricole, demarand mai multe proiecte si Planuri Urbanistice Zonale (PUZ);<br>2011- compania incepe activitatea in domeniul constructiilor executand diverse lucrari de amenajare, modernizare si reabilitare si isi reinnoieste parcul auto in vederea dezvoltarii serviciului de inchiriere;&nbsp;<br>2012 - se continua activitatea in constructii prin inceperea lucrarilor de mansardare la imobilul de Timisoara de pe str. Timis nr. 20, in urma acestor lucrari rezultand 12 apartamente a cate doua camere, confort 1, decomandate a cate 60mp fiecare;<br>2013 - compania finalizeaza lucrarile de mansardare de pe str. Timis, cele 12 apartamente fiind adaugate la patrimoniul imobiliar al companiei si intrand in circuitul de inchiriere.\r\n		    </p>		    		                    ', 'yes'),
(2, 1, 'ECHIPA', '<p>                    Alin Fales - asociat si administrator al companiei incepand cu anul 2007 pana in prezent, licentiat in drept, cu expertiza in investitii imobiliare, bursa si sectorul auto;\r\nAlfredo Campolmi - asociat incepand cu anul 2007, fost director ENEL Italia, cu experienta in imobiliare si bursa;\r\nRadu Puica - asociat incepand cu anul 2011, arhitect, cu expertiza in investitii imobiliare si proiectare                </p>', 'yes'),
(3, 1, 'ARII DE EXPERTIZA', '                                        <p><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Agar</span><span style="background-color: rgb(255, 255, 255); font-family: helvetica; font-size: 14px; text-align: justify;">&nbsp;Company este o companie cu capital romano-italian avand ca domenii de activitate imobiliare, constructii si servicii.</span></p><p><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Compania este certificata ISO 9001, ISO 14001 si ISO 18001.</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Agar Company ofera deasemenea consultanta in Managementul Calitatii si de Devoltare si Audit de Mediu</span><br></p>                                ', 'yes'),
(7, 7, '', '<p><span style="text-align: -webkit-center; background-color: rgb(255, 255, 255);">Ne cerem scuze, aceasta sectiune nu este disponibila momentan.</span><br></p>', 'no'),
(8, 2, 'CONSTRUCTII', '<p><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">AGAR COMPANY este specializata in constructia de case si vile noi in stil traditional, modern, renovare de case vechi si apartamente precum si in lucrari de amenajari interioare, instalatiir electrice si sanitare.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Suntem o firma de constructii cu experienta si dinamica, formata dintr-o echipa de profesionisti.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Oferim competenta si echipamentele pentru toate tipurile de constructii, indiferent de dimensiune si complexitate, timp si buget, facand ca proiectul si visele dvs sa devina realitate.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pana la finalizarea proiectului exista o "supraveghere stricta" in toate etapele de constructive, oferim regulat rapoarte de lucru, atasat cu fotografii, pentru fiecare faza de constructie.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru fiecare din proiectele si lucrarile nostre vom folosi materiale de inalta calitate si vom acorda garantie atat pentru material cat si pentru serviciile prestate.&nbsp;</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Prin acest mod de lucru am reusit sa construim case sigure si functionale</span><br></p>', 'no'),
(9, 2, 'RENOVARI', '<span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Renovarile de cladiri si apartamente istroice este una din ramurile in care echipa AGAR COMPANY a dobandit expertienta in decursul anilor.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru fiecare din lucrari sunt folosite materiale de inalta calitate se acorda garantie atat pentru material cat si pentru serviciile prestate.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><p><span style="background-color: rgb(255, 255, 255); font-family: helvetica; font-size: 14px; word-spacing: 4px;">Specialistii echipei din departamentul de constructii, va vor oferi solutiile optime, astfel incat lucrarea de renovare sa fie conform standardelor estetice si functionale dorite.</span><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">prestate.&nbsp;</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Prin acest mod de lucru am reusit sa construim case sigure si functionale</span><br></p>', 'no'),
(10, 2, 'PROIECTARE', '<p><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Echipa de arhitecti ai companiei examineaza cu atentie caietului de sarcini si va vor propune o gama larga de proiecte de arhitectura in functie de necesitatile dumneavoastra.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Indiferent de natura constructiei, echipa AGAR COMPANY va ofera prin serviciul de proiecatre solutii pentru o gama larga de constructii: constructii civile (case la rosu si case la cheie) si industriale (hale/structuri) ori parti ale acestora lucrari de invelitori, sarpante, terase la constructii.</span><br></p>', 'no'),
(11, 2, 'AMENAJARI INTERIOARE', '<p><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Daca doriti amenajarea unui spatiu de lucru, a unei locuinte sau a unui spatiu de recreere, AGAR COMPANY e in masura sa va ajute sa decideti intre o varietate de propuneri si sugestii creative precum si functionale.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Agar Company realizeaza o diversitate de amenajari interioare: lucrari de instalatii sanitare si electrice, lucrari de izolatii termice, fonice si anticorozive, lucrari de pardosire si placare a peretilor, lucrari de vopsitorie, zugraveli si ipsoserie, lucrari de tamplarie si dulgherie.</span><br></p>', 'no'),
(12, 2, 'CONSULTANTA', '                                        <p><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">AGAR COMPANY va ofera consultanta si asistenta in: proiecte case, certificate de urbanism, autorizatii de construire, avize, studii geotehnice.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">De asemenea companai colaboreaza indeaproape cu producatori de materiale si firme specializate pentru a obtine intotdeauna cele mai bune rezultate la preturi competitive si ofera asistenta tehnica pe perioada executiei lucrarilor.</span></p>                                ', 'no'),
(13, 3, 'INCHIRIERI', '                                                                                <div style="font-family: Arial, Verdana; font-size: 10pt; font-style: normal; font-variant: normal; font-weight: normal; line-height: normal;">AGAR Company INCHIRIERI AUTO va pune la dispozitie o gama variata de autoturisme dotate si verificate conform standardelor internationale.<br>\r\nSuntem o echipa de profesionisti iar personalul nostru va sta la dispozitie pentru a va intampina asteptarile: consultanta profesionala la alegerea autoturismului si pe perioada inchirierii, soferi personali profesionisti, asistenta tehnica specializata.<br>Pentru detalii, va rugam consultati <a href="http://www.rent-a-car-timisoara.com/" target="_blank"><font color="#3366ff">pagina</font></a> dedicata.</div><p style="font-family: Arial, Verdana; font-size: 10pt; font-style: normal; font-variant: normal; font-weight: normal; line-height: normal;">                                              </p><div style="text-align: right;"><span style="font-size: 12px; "><a href="http://www.rent-a-car-timisoara.com/" target="_blank">CITESTE MAI MULT</a></span></div>                                                                                ', 'no'),
(14, 3, 'TRANSPORT AEROPORT', '                                                                                                                                                                                    <p style="font-family: Arial, Verdana; font-size: 10pt; font-style: normal; font-variant: normal; font-weight: normal; line-height: normal;"><span style="font-size: 14px; font-family: helvetica; word-spacing: 4px; background-color: rgb(255, 255, 255);">Indiferent daca beneficiati de serviciile noastre de inchiriere sau nu, compania noastra va ofera serviciul de transfer la Aeroportul International "Traian Vuia" din Timisoara sau la Aeroportul International Arad.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-size: 14px; font-family: helvetica; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pretul acestui serviciu variaza in functie de numarul de persoane.</span></p><p style="font-family: Arial, Verdana; font-size: 10pt; font-style: normal; font-variant: normal; font-weight: normal; line-height: normal;"><font face="helvetica"><span style="font-size: 14px; word-spacing: 4px;">Pentru detalii, va rugam consultati</span></font><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">&nbsp;</span><a href="http://www.rent-a-car-timisoara.com/servicii-speciale.html" target="_blank" style="font-family: helvetica; font-size: 14px; word-spacing: 4px; color: rgb(7, 147, 200); text-decoration: none;">pagina</a><font style="font-size: 10pt;">&nbsp;</font><span style="font-family: helvetica; font-size: 14px; background-color: rgb(255, 255, 255); word-spacing: 4px;">&nbsp;</span><span style="font-family: helvetica; font-size: 14px; background-color: rgb(255, 255, 255); word-spacing: 4px;">dedicata.</span></p><p style="font-family: Arial, Verdana; font-size: 10pt; font-style: normal; font-variant: normal; font-weight: normal; line-height: normal; text-align: right;"><font face="helvetica"><span style=" font-family: helvetica; font-size: 12px; word-spacing: 4px;"><a href="http://www.rent-a-car-timisoara.com/servicii-speciale.html" target="_blank">CITESTE MAI MULT</a></span></font></p>                                                                                                                                                ', 'no'),
(15, 3, 'SOFER PERSONAL', '                    <p><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru confortul dvs, va oferim posibilitatea inchirierii unui sofer personal alaturi de autoturismul ales.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Soferul va va sta la dispozitie pe perioada dorita.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru detalii, va rugam consultati&nbsp;</span><a href="http://www.rent-a-car-timisoara.com/servicii-speciale.html" target="_blank" style="font-family: helvetica; font-size: 14px; word-spacing: 4px; color: rgb(7, 147, 200); text-decoration: none;">pagina</a><span style="background-color: rgb(255, 255, 255); font-family: helvetica; font-size: 14px; word-spacing: 4px;">&nbsp;</span><span style="background-color: rgb(255, 255, 255); font-family: helvetica; font-size: 14px; word-spacing: 4px;">dedicata.</span></p><p style="text-align: right;"><a href="http://www.rent-a-car-timisoara.com/servicii-speciale.html" target="_blank" style="font-family: helvetica; font-size: 12px; word-spacing: 4px;">CITESTE MAI MULT</a></p>                ', 'no'),
(16, 3, 'TRACTARI AUTO', '                                        <p><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Compania noastra va ofera asistenta tehnica si tractare in cazul unui accident sau a unei defectiuni care va pune in imposibilitatea de a va continua drumul.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Echipa noastra pentru cazurile de avarie va reactiona prompt si va va asista cu profesionalism.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Acest serviciu este diponibil NON STOP.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru detalii, va rugam consultati&nbsp;</span><a href="http://www.rent-a-car-timisoara.com/servicii-speciale.html" target="_blank" style="font-family: helvetica; font-size: 14px; word-spacing: 4px; color: rgb(7, 147, 200); text-decoration: none;">pagina</a><span style="background-color: rgb(255, 255, 255); font-family: helvetica; font-size: 14px; word-spacing: 4px;">&nbsp;</span><span style="background-color: rgb(255, 255, 255); font-family: helvetica; font-size: 14px; word-spacing: 4px;">dedicata.</span></p><p style="text-align: right;"><a href="http://www.rent-a-car-timisoara.com/servicii-speciale.html" target="_blank" style="font-family: helvetica; font-size: 12px; word-spacing: 4px;">CITESTE MAI MULT</a></p>                                ', 'no'),
(17, 3, 'LEASING OPERATIONAL', '                    <p><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Agar Company va ofera servicii de inchirieri autoturisme pe termen lung ( in sistem de Leasing Operational cu servicii incluse).</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Parcul auto este compus din autoturisme noi, intretinute conform prescriptiilor producÄƒtorilor, astfel, prin serviciul de leasing, autoturismul de care veti beneficia este in cea mai buna stare de functionare si conform normelor de siguranta.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru detalii, va rugam consultati&nbsp;</span><a href="http://www.rent-a-car-timisoara.com/operational-leasing.html" target="_blank" style="font-family: helvetica; font-size: 14px; word-spacing: 4px; color: rgb(7, 147, 200); text-decoration: none;">pagina</a><span style="background-color: rgb(255, 255, 255); font-family: helvetica; font-size: 14px; word-spacing: 4px;">&nbsp;</span><span style="background-color: rgb(255, 255, 255); font-family: helvetica; font-size: 14px; word-spacing: 4px;">dedicata.</span></p><p style="text-align: right;"><a href="http://www.rent-a-car-timisoara.com/operational-leasing.html" target="_blank" style="font-family: helvetica; font-size: 12px; word-spacing: 4px;">CITESTE MAI MULT</a></p>                ', 'no'),
(18, 4, 'VANZARI AUTOTURISME', '                    <span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">AGAR COMPANY detine un parc auto cu o diversitate de autoturisme, de la cele de fiecare zi, pana la autoturisme de lux si utilitare.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Compania selecteaza cu atentie autoturismele ce urmeaza sa fie puse in vanzare si prin asta va ofera o varietate de marci si modele la standarde inatlte.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">AGAR COMPANY va asigura un istoric detaliat al autoturismelor, iar dvs puteti fi siguri ca veti avea un autoturism la un pret foarte bun si o sursa de incredere.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru detalii, va rugam consultati </span><div class="text_link" style="clear: none; display: inline; font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://agarcars.com/" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">pagina</a></div><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"> dedicata.</span><div style="text-align: right;"><br class="Apple-interchange-newline"><span style="color: rgb(7, 147, 200); font-family: helvetica; font-size: 9px; font-weight: bold; text-align: left; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://agarcars.com/" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">CITESTE MAI MULT</a></span></div>                ', 'no'),
(19, 5, 'INCHIRIERI', '                    <span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">AGAR Company APARTHOTEL va pune la dispozitie apartamente in zona centrala a orasului, la standarde inalte de confort si utilate ultra modern.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Ideale pentru cazare pe timpul calatoriilor de afaceri, de weekend, de vacanta, apartamentele noastre sunt cea mai buna alternativa a hotelurilor, oferindu-va conditii excelente si, in acelasi timp, intimitatea propriului camin.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru detalii, va rugam consultati </span><div class="text_link" style="clear: none; display: inline; font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://rentintm.com/rezervare.html" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">pagina</a></div><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"> dedicata.</span><div style="text-align: right;"><br class="Apple-interchange-newline"><span style="color: rgb(7, 147, 200); font-family: helvetica; font-size: 9px; font-weight: bold; text-align: left; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://rentintm.com/rezervare.html" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">CITESTE MAI MULT</a></span></div>                ', 'no'),
(20, 5, 'INCHIRIERI PE TERMEN LUNG', '<span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">AGAR Company APARTHOTEL va ofera servicii de inchiriere pe termen lung.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Daca doriti alternativa la contractele de inchiriere obisnuite, cu constrangerile de rigoare, alternativa noastra este cea mai buna alegere!&nbsp;</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Va rugam sa ne contactati pentru a va face cea mai buna oferta.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru detalii, va rugam consultati&nbsp;</span><div class="text_link" style="clear: none; display: inline; font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://rentintm.com/long-term-rental.html" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">pagina</a></div><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">&nbsp;dedicata.</span><div style="text-align: right;"><div class="read_more_links_service" style="font-size: 9px; font-family: helvetica; font-weight: bold; color: rgb(7, 147, 200); float: right; margin-top: 15px; text-align: left; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://rentintm.com/long-term-rental.html" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">CITESTE MAI MULT</a></div><br style="font-family: helvetica; font-size: 14px; text-align: left; word-spacing: 4px; background-color: rgb(255, 255, 255);"></div>', 'no'),
(21, 6, 'VANZARI TERENURI', '                                                            <span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">AGAR COMPANY detine o experienta de peste 7 ani in domeniul vanzarilor de terenuri intravilane si extravilane in regiunea de vest a tarii.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Printre liderii pe piata imobiliara din regiune, pe langa o oferta de vanzare variata, compania va ofera consultanta si intermediere in achizitionarea sau vanzarea de terenuri.</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru detalii, va rugam consultati </span><div class="text_link" style="clear: none; display: inline; font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://roimobiliare.net/terenuri.php" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">pagina</a></div><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"> dedicata.</span><div style="text-align: right;"><br class="Apple-interchange-newline"><span style="color: rgb(7, 147, 200); font-family: helvetica; font-size: 9px; font-weight: bold; text-align: left; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://roimobiliare.net/terenuri.php" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">CITESTE MAI MULT</a></span></div>                                                ', 'no'),
(22, 6, 'VANZARI LOCUINTE', '<span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Daca doriti sa achizitionati o lucuinta, compania noastra va ofera mai multe solutii, calibrate pe dorintele dvs. AGAR COMPANY ofera spre vanzare locuinte in Timisoara la preturi fara competitie!</span><br style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">Pentru detalii, va rugam consultati&nbsp;</span><div class="text_link" style="clear: none; display: inline; font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://roimobiliare.net/apartamente.php" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">pagina</a></div><span style="font-family: helvetica; font-size: 14px; word-spacing: 4px; background-color: rgb(255, 255, 255);">&nbsp;dedicata.</span><div style="text-align: right;"><div class="read_more_links_service" style="font-size: 9px; font-family: helvetica; font-weight: bold; color: rgb(7, 147, 200); float: right; margin-top: 15px; text-align: left; word-spacing: 4px; background-color: rgb(255, 255, 255);"><a href="http://roimobiliare.net/apartamente.php" target="_blank" style="text-decoration: none; color: rgb(7, 147, 200);">CITESTE MAI MULT</a></div><br style="font-family: helvetica; font-size: 14px; text-align: left; word-spacing: 4px; background-color: rgb(255, 255, 255);"></div>', 'no'),
(23, 8, 'CONSULTANTA', '<span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">AGAR COMPANY va ofera consultanta in Managementul Calitatii si de Dezvoltare, instrument necesar pentru optimizarea productivitatii si a relatiei companiei dvs cu clientii si furnizorii sai.</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Pentru mai multe detalii, va rugam sa ne&nbsp;</span><div class="text_link" style="clear: none; display: inline; font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><a href="http://agar.dev/contact/" target="_blank" style="color: rgb(7, 147, 200); text-decoration: none;">contactati</a></div><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">.</span>', 'yes'),
(24, 8, 'CERTIFICARI', '<span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Compania noastra va ofera sprijin in obtinerea urmatoarelor certificate:&nbsp;</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Sisteme de Management al Calitatii - ISO 9001</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Sisteme de Management al Mediului - ISO 14001</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Sisteme de Management al Sanatatii si Securitatii Ocupationale - OHSAS 18001</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Sisteme de Management al Responsabilitatii Sociale â€“ Social Accountability 8000</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Sisteme de Management al Securitatii Informatiei - ISO/IEC 27001</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Sisteme de Management al Energiei - ISO 16001</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Sistem de Management al Sigurantei Alimentelor - HACCP / ISO 22000</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Pentru mai multe detalii, va rugam sa ne&nbsp;</span><div class="text_link" style="clear: none; display: inline; font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><a href="http://agar.dev/contact/" target="_blank" style="color: rgb(7, 147, 200); text-decoration: none;">contactati</a></div><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">.&nbsp;</span>', 'yes'),
(25, 8, 'AUDIT', '<span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">AGAR COMPANY realizeaza, in conformitate cu metodologii utilizate si recunoscute in Uniunea Europeana, Audituri de Mediu conform standardelor de referinta si cerintelor clientului.</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Pentru mai multe detalii, va rugam sa ne&nbsp;</span><div class="text_link" style="clear: none; display: inline; font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><a href="http://agar.dev/contact/" target="_blank" style="color: rgb(7, 147, 200); text-decoration: none;">contactati</a></div><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">.</span>', 'yes'),
(26, 9, 'CONTACT', '<span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">str. Lucian Blaga nr.1 ap.27, 300001, Timisoara</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Tel: +40 - 762 - 09999</span><br style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);"><span style="font-family: helvetica; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">office@agarcompany.com</span>', 'no');

-- --------------------------------------------------------

--
-- Table structure for table `projects`
--

CREATE TABLE IF NOT EXISTS `projects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(128) NOT NULL,
  `text` text NOT NULL,
  `image` varchar(128) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Dumping data for table `projects`
--

INSERT INTO `projects` (`id`, `title`, `text`, `image`) VALUES
(2, 'CONSTRUCTIE CASA PENTRU LOCUIT', '<span style="font-family: helvetica; font-size: 12px; text-align: justify; background-color: rgb(255, 255, 255);">Constructia unei vile cu etaj si mansarda.</span><div><br></div>', '68287-penultima_lucrare.jpg'),
(3, 'REABILITARE BLOC DE LOCUINTE', '<span style="font-family: helvetica; font-size: 12px; text-align: justify; background-color: rgb(255, 255, 255);">Reabilitarea unui bloc de locuinte din zona centrala a orasului, ce a inclus: izolare termica, constructia acoperisului si mansardare, renovarea fatadei.</span>', '127035-ultima_lucrare.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `types`
--

CREATE TABLE IF NOT EXISTS `types` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=10 ;

--
-- Dumping data for table `types`
--

INSERT INTO `types` (`id`, `name`) VALUES
(1, 'ACASA'),
(5, 'APARTHOTEL'),
(2, 'CONSTRUCTII'),
(8, 'CONSULTANTA'),
(9, 'CONTACT'),
(6, 'IMOBILIARE'),
(4, 'PARC AUTO'),
(7, 'PLAY & WIN'),
(3, 'RENT A CAR');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `user`, `password`) VALUES
(1, 'admin', '03053c8c3fafda9f1a580deb7530ef30');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
